# This workflow will create an AP world release and store builds to it when an vX.Y.Z tag is pushed

name: Release AP World

on:
  push:
    tags:
      - v*.*.*

env:
  # Name of AP World
  AP_WORLD_NAME: Soul Blazer
  # Name of world's directory (in the worlds directory).
  AP_WORLD_DIR: soulblazer
  # Will be redefined in subsequent steps, but it makes the syntax highlighter happy.
  RELEASE_VERSION: v0.0.0
  VERSION_NUM: v0.0.0
  AP_WORLD_PATH: ""

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "VERSION_NUM=${GITHUB_REF#refs/v*/}" >> $GITHUB_ENV
      - name: Checkout APWorld Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: worlds/${{ env.AP_WORLD_DIR }}
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '~3.12.7'
          check-latest: true
      - run: pip install --upgrade setuptools>=75,<81
      - name: Update World Version in Manifest
        run:  |
          cd worlds/${{ env.AP_WORLD_DIR }}
          json="$(jq '.world_version = "${{ env.VERSION_NUM }}"' archipelago.json)"
          echo "${json}" > archipelago.json
      - name: Create AP World Archive # Press the button, Max!
        run: |
          python Launcher.py "Build APWorlds" -- "${{ env.AP_WORLD_NAME }}"
          echo "AP_WORLD_PATH=build/apworlds/${{ env.AP_WORLD_DIR }}.apworld" >> $GITHUB_ENV
      # - name: Create AP World Archive
      #   run: |
      #     mkdir dist
      #     cd worlds
      #     zip -r ../dist/${{ env.AP_WORLD_DIR }}.apworld ${{ env.AP_WORLD_DIR }}
      #     echo "AP_WORLD_PATH=dist/${{ env.AP_WORLD_DIR }}.apworld" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true  # don't publish right away
          prerelease: false
          name: ${{ env.AP_WORLD_NAME }} APWorld ${{ env.RELEASE_VERSION }}
          files: ${{ env.AP_WORLD_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
